change: added option for reading sample ids from a file i.e. enable use of fixed IDs instead of always randomizing.

diff --git a/sead.query.test/Infrastructure/Mocks/FacetContext/PostgreSQL/Data/create-sample b/sead.query.test/Infrastructure/Mocks/FacetContext/PostgreSQL/Data/create-sample
--- a/sead.query.test/Infrastructure/Mocks/FacetContext/PostgreSQL/Data/create-sample
+++ b/sead.query.test/Infrastructure/Mocks/FacetContext/PostgreSQL/Data/create-sample
@@ -22,6 +22,7 @@ g_sample_count=10
 g_folder=$g_script_dir/initdb.d
 g_timestamp=$(date +'%Y%m%d_%H%M%S')
 g_dump_format=csv
+g_fixed_ids_file=
 
 if [ -f ~/vault/.default.sead.server ]; then
     g_host=`cat ~/vault/.default.sead.server`
@@ -40,13 +41,15 @@ function usage()
     echo "usage: create-sample [OPTIONS...] DBNAME"
     echo "Creates a sample of the database."
     echo "Options:"
-    echo "   --host HOSTNAME            host name"
-    echo "   --user USERNAME            user name"
-    echo "   --port PORT                host port "
-    echo "   --folder FOLDER            output folder name"
-    echo "   --sample-count COUNT       size of each sample group (default: 10)"
+    echo "   --host HOSTNAME            host name or IP address (default: $g_host)"
+    echo "   --user USERNAME            user name (default: $g_user)"
+    echo "   --port PORT                host port (default: $g_port)"
+    echo "   --sample-count COUNT       size of each sample group (default: $g_sample_count)"
     echo "   --database DBNAME          database name"
     echo "   --format FORMAT            dump format (default: csv)"
+    echo "   --fixed-ids FILENAME       Filename with fixed sample ids (default: NONE - random ids)"
+    echo "   --folder FOLDER            output folder name (default: $g_folder)"
+    echo "   --help                     show this help message"
     exit 64
 }
 
@@ -75,6 +78,9 @@ do
             if [ "$g_dump_format" != "csv" ] && [ "$g_dump_format" != "insert" ]; then
                 usage "[$g_timestamp]: Unknown format $g_dump_format"
             fi
+        ;;
+        --fixed-ids)
+            g_fixed_ids_file="$2"; shift 2;
         ;;
         --*)
             usage "[$g_timestamp]: Unknown option $1"
@@ -137,15 +143,32 @@ function dump_data()
     # 2) create dump_sample and copy its data and fill it with data from pubic schema
 
     drop_schema "dump_sample"
-    echo "create schema dump_sample;"                          > $g_folder/_materialize_data.sql
+    echo "-- THIS IS A TEMPORARY SCRIPT  GENERATED BY create-sample SCRIPT"    > $g_script_dir/materialize_data.sql
+    echo "create schema dump_sample;"                                         >> $g_script_dir/materialize_data.sql
+
+    if [ "$g_fixed_ids_file" != "" ]; then
+        if [ ! -f $g_fixed_ids_file ]; then
+            echo "[$g_timestamp]: file $g_fixed_ids_file not found"            >&2
+            exit 1
+        fi
+        echo "\\copy sample.physical_samples_fixture from stdin with (format csv, header true);" >> $g_script_dir/materialize_data.sql 
+        cat "${g_fixed_ids_file}"                                              >> $g_script_dir/materialize_data.sql
+        echo ""                                                                >> $g_script_dir/materialize_data.sql 
+        echo "\\."                                                             >> $g_script_dir/materialize_data.sql 
+    else
+        echo "insert into sample.physical_samples_fixture (physical_sample_id)"     >> $g_script_dir/materialize_data.sql   
+        echo "   select distinct physical_sample_id "                          >> $g_script_dir/materialize_data.sql    
+        echo "   from sample.sample_per_datatype(5);"                          >> $g_script_dir/materialize_data.sql    
+    fi;
+    echo ""                                                                    >> $g_script_dir/materialize_data.sql 
 
     for view in $(psql $g_credentials -t -c "select table_name from information_schema.views where table_schema='sample';")
     do
-        echo "create table dump_sample.$view as select * from sample.$view;" >> $g_folder/_materialize_data.sql
+        echo "create table dump_sample.$view as select * from sample.$view;" >> $g_script_dir/materialize_data.sql
     done
 
-    execute_sql_file "$g_folder/_materialize_data.sql"
-    execute_sql "select drop_columns_by_pattern('dump_sample', array['date_updated', '%uuid', 'age_range']);"
+    execute_sql_file "$g_script_dir/materialize_data.sql"
+    execute_sql "select sample.drop_columns_by_pattern('dump_sample', array['date_updated', '%uuid', 'age_range']);"
 
     # 3) dump each public table subset (in schema dump_sample) as CSV or inserts
 
@@ -161,8 +184,9 @@ function dump_data()
             psql $g_credentials --quiet -t -c "copy dump_sample.$table to stdout with csv header;" > $g_folder/csv/$table.csv
             if [ $(tail -n +2 "$g_folder/csv/$table.csv" | wc -l) -eq 0 ]; then
                 rm "$g_folder/csv/$table.csv"
-                echo "File $g_folder/csv/$table.csv was removed because it has no data rows."
+                # echo "File $g_folder/csv/$table.csv was removed because it has no data rows."
             fi
+            # echo -n "."
         done
         echo "[$g_timestamp]: Successfully exported data to CSV files." >&2
     else
@@ -172,7 +196,7 @@ function dump_data()
         echo "commit;"                                                                            >> $g_folder/09-data.sql
     fi
 
-    rm -f $g_folder/_materialize_data.sql
+    # rm -f $g_script_dir/materialize_data.sql
 
     if [ -f $g_folder/09-data.sql ]; then
         sed -i 's/dump_sample\./public./g' $g_folder/09-data.sql
